### ISSUE TITLE
Creating users ( Also some documentation?)

### ISSUE THREAD

**Issue by Gabisonfire** [codingchili/kbn-authentication-plugin#24]
Hey,

Trying to use your (awesome) plugin but after a lot of fiddling I cant for the life of me figure out how to create a user. I've tried with the argon lib to manually generate a password. I'm only able to login with the default "username" "password" and all I see on the authentication panel is "default" group.
When I put in a user of my own, the authentication fails.

Scrolling through the code, i can see the file storage has a "create" function. I'm guessing I'm missing something.

Also, does the LDAP mode supports ActiveDirectory?

Tried with 5.4.0 and 5.6.2
Everything runs in docker.

Thanks for your work!

**Comment by codingchili** [comment]
Hello, 

Could you upload your modified users.json?

The default group is read from the user in users.json. If LDAP is used then the users groups will be displayed instead. The purpose of the groups was to manage access control to different dashboards, this feature is not implemented yet.

Do you get an error when the authentication fails? 

The 'create' function is used in the tests, I have thought about making it available from the command line. I will open a new issue to fix that and another to improve the docs.

The LDAP mode has only been tested with ApacheDS.

Thanks for submitting an issue!

**Comment by codingchili** [comment]
I made the create method for adding users available from the command line.

Example:
`node adduser.js USERNAME PASSWORD`

Should work for file and mongoDB storage, not LDAP.

**Comment by Gabisonfire** [comment]
Thank you so much, ill upload you the config file tomorrow, I dont have it on this computer.

**Comment by Gabisonfire** [comment]
This is our users.json inside our container
The salt is  "somesalt" and the password is "potato"

`{
        "username": {
                "uid": "someotheruser",
                "password": "$argon2i$v=19$m=16384,t=4,p=1$c29tZXNhbHQ$OPo8d9+iz4qijYB3UCv7Dq3kVtxbo/9PrcSwJt2doDM",
                "groups": ["default"],
                "secret": {
                        "verified": true
                }
        },
        "test-username": {
                "secret": {
                        "key": "IVHGIYL5EF3TSRJGJV3UYR3UHE",
                        "verified": true
                }
        }
}
`

**Comment by codingchili** [comment]
Ah yes, two things are going on here. 

1. for the file based storage we use json keys for fast user lookups. This is actually the "username" part in your users.json. If you login with username:potato it will work (but then the 2 factor authentication would fail, since it uses the uid.).

2. the username is also stored within the object of the map. This is done to comply with the API and the other storage options.

So the solution here would be to duplicate your username, for example:
`{"someotheruser": { "uid": "someotheruser", ....}, "someotheruser2": {"uid": "someotheruser2"}... }`

I have thought about changing it, and mapping the KEY of the map entry to UID after the lookup is done. Maybe I should fix this, because its not really obvious, especially when the default username is "username". But maybe I can get away with it, if the adduser is used instead...

Thanks for providing the file.

**Comment by Gabisonfire** [comment]
Thanks for answering! Now I understand :)
I think it's fine the way it is, but it could be a good idea to provide this information in the readme.

Again, thank you for your great work!

**Comment by Gabisonfire** [comment]
Somehow doing it manually didnt work but using your script worked perfectly!

**Comment by iNERO9** [comment]
What version of Node/NPM are  you using?
